### ISSUE TITLE
[Bug] Tooltip on icons loader won't disappear

### ISSUE THREAD

**Issue by GwonHeeJun** [gridaco/assistant#73]
### How to make this bug?

1. Drag & Drop Icons
2. See assistant ui
3. Can see not deleted tooltips

### ScreenShot
![스크린샷 2021-02-04 오전 2 28 02](https://user-images.githubusercontent.com/40719546/106785309-9bca9200-6690-11eb-84c8-72eb7a3d8587.png)

### Memo
There is no significant impact on UX, but there is a need to modify it.

**Comment by softmarshmallow** [comment]
Reference: https://github.com/mui-org/material-ui/issues/12246
