### ISSUE TITLE
Analytics won't work on figma due to cookie / indexdb block on figma iframe

### ISSUE THREAD

**Issue by softmarshmallow** [gridaco/assistant#74]
Supporting GA seems like a possible feature looking at a "Rename It" Plugin.
![bridged assistant analytics wont work on figma](https://user-images.githubusercontent.com/16307013/107394779-8eede880-6b3f-11eb-9aa5-95da3c709dee.png)

**Approaches**
- remote GA call
- enabling cookies with some tweaks
- other 3rd solution

## References
- https://stackoverflow.com/questions/41067069/javascript-errors-localstorage-cookie-loading-sandboxed-iframe-within-chrome
- https://github.com/firebase/firebase-js-sdk/issues/4372

## Working branch
- https://github.com/bridgedxyz/assistant/tree/feature/analytics

**Comment by softmarshmallow** [comment]
Update - need research
![image](https://user-images.githubusercontent.com/16307013/113357411-f0cc1100-937e-11eb-8b2e-18b0d39f9216.png)

https://github.com/basiclines/figma-super-tidy/blob/master/src/utils/Tracking.js
https://github.com/basiclines/figma-super-tidy/blob/master/src/Core.js#L123


https://figmaplugins.slack.com/archives/CHPTY6TFD/p1613083318167400

**Comment by softmarshmallow** [comment]
Using Measurement api seems to be like a approach.

https://developers.google.com/analytics/devguides/collection/protocol/ga4/sending-events?client_type=gtag#send_an_event

Could not make it work. cannot find information about what `app_instance_id` was. (cannot retrieve it from web)

via gtag api won't work either.

**Comment by softmarshmallow** [comment]
Found the solution i think.

https://ga-dev-tools.appspot.com/ga4-event-builder/

here, we can test the analytics4. which app instance id was not required.

**Comment by softmarshmallow** [comment]
Done by hosting the plugin to web.

**Comment by myflashlab** [comment]
Seems like specifying `app_instance_id` is mandatory. Am I missing something?

<img width="417" alt="Screenshot 2022-05-12 at 09 07 34" src="https://user-images.githubusercontent.com/1692948/168012240-228eb4df-96d6-4f47-9916-dd390bbfdbd6.png">

**Comment by softmarshmallow** [comment]
At some point. I gave up this approach having analytics directly in figma plugin iframe. Instead, i hosted the plugin ui as a general website with external url with indexeddb, + (other apis available) which is best for using existing analytics services without any unexpectations ;)
